language: php

php:
  - 7.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
