version: '3'

services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    ports:
      - "1443:443"
    volumes:
      - ./public:/var/www/html/public
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    environment:
      - APP_ENV=docker

  artisan:
    build:
      context: .
    entrypoint: php artisan
    command:
      - queue:listen
    volumes:
      - .:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    environment:
      - APP_ENV=docker

  phpunit:
    build:
      context: .
    entrypoint: vendor/bin/phpunit
    volumes:
      - .:/var/www/html
    links:
      - postgres-testing
    environment:
      - APP_ENV=testing
      - DB_HOST=postgres-testing
      - DB_PASSWORD=postgres

  postgres:
    image: postgres:10
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres-testing:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:4

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025"
